// ORDER
export const ORDER_READ_PERMISSION = 'ORDER_READ_PERMISSION';
export const ORDER_UPDATE_PERMISSION = 'ORDER_UPDATE_PERMISSION';
export const ORDER_CREATE_PERMISSION = 'ORDER_CREATE_PERMISSION';
export const ORDER_DELETE_PERMISSION = 'ORDER_DELETE_PERMISSION';

// USER
export const USER_READ_PERMISSION = 'USER_READ_PERMISSION';
export const USER_UPDATE_PERMISSION = 'USER_UPDATE_PERMISSION';
export const USER_CREATE_PERMISSION = 'USER_CREATE_PERMISSION';
export const USER_DELETE_PERMISSION = 'USER_DELETE_PERMISSION';

// BOOK
export const BOOK_READ_PERMISSION = 'BOOK_READ_PERMISSION';
export const BOOK_UPDATE_PERMISSION = 'BOOK_UPDATE_PERMISSION';
export const BOOK_CREATE_PERMISSION = 'BOOK_CREATE_PERMISSION';
export const BOOK_DELETE_PERMISSION = 'BOOK_DELETE_PERMISSION';

// EVENT
export const EVENT_READ_PERMISSION = 'EVENT_READ_PERMISSION';
export const EVENT_UPDATE_PERMISSION = 'EVENT_UPDATE_PERMISSION';
export const EVENT_CREATE_PERMISSION = 'EVENT_CREATE_PERMISSION';
export const EVENT_DELETE_PERMISSION = 'EVENT_DELETE_PERMISSION';

// LIBRARY
export const LIBRARY_READ_PERMISSION = 'LIBRARY_READ_PERMISSION';
export const LIBRARY_UPDATE_PERMISSION = 'LIBRARY_UPDATE_PERMISSION';
export const LIBRARY_CREATE_PERMISSION = 'LIBRARY_CREATE_PERMISSION';
export const LIBRARY_DELETE_PERMISSION = 'LIBRARY_DELETE_PERMISSION';

// STATISTIC
export const STATISTIC_READ_PERMISSION = 'STATISTIC_READ_PERMISSION';

// STORE
export const STORE_READ_PERMISSION = 'STORE_READ_PERMISSION';
export const STORE_UPDATE_PERMISSION = 'STORE_UPDATE_PERMISSION';
export const STORE_CREATE_PERMISSION = 'STORE_CREATE_PERMISSION';
export const STORE_DELETE_PERMISSION = 'STORE_DELETE_PERMISSION';

export const LIBRARIAN_PERMISSIONS: string[] = [
    ORDER_READ_PERMISSION,
    ORDER_UPDATE_PERMISSION,
    ORDER_CREATE_PERMISSION,
    ORDER_DELETE_PERMISSION,

    USER_READ_PERMISSION,

    BOOK_READ_PERMISSION,

    EVENT_READ_PERMISSION,

    LIBRARY_READ_PERMISSION,

    STORE_READ_PERMISSION,
];

export const BIBLIOGRAPHER_PERMISSIONS: string[] = [
    ORDER_READ_PERMISSION,

    USER_READ_PERMISSION,
    USER_UPDATE_PERMISSION,
    USER_CREATE_PERMISSION,

    BOOK_READ_PERMISSION,
    BOOK_UPDATE_PERMISSION,
    BOOK_CREATE_PERMISSION,

    EVENT_READ_PERMISSION,

    LIBRARY_READ_PERMISSION,

    STORE_READ_PERMISSION,
    STORE_UPDATE_PERMISSION,
    STORE_CREATE_PERMISSION,
];

export const ADMINISTRATOR_PERMISSIONS: string[] = [
    ORDER_READ_PERMISSION,

    USER_READ_PERMISSION,
    USER_DELETE_PERMISSION,
    USER_UPDATE_PERMISSION,
    USER_CREATE_PERMISSION,

    BOOK_READ_PERMISSION,
    BOOK_UPDATE_PERMISSION,
    BOOK_CREATE_PERMISSION,
    BOOK_DELETE_PERMISSION,

    EVENT_READ_PERMISSION,
    EVENT_UPDATE_PERMISSION,
    EVENT_CREATE_PERMISSION,
    EVENT_DELETE_PERMISSION,

    LIBRARY_READ_PERMISSION,
    LIBRARY_UPDATE_PERMISSION,
    LIBRARY_CREATE_PERMISSION,
    LIBRARY_DELETE_PERMISSION,

    STATISTIC_READ_PERMISSION,

    STORE_READ_PERMISSION,
    STORE_UPDATE_PERMISSION,
    STORE_CREATE_PERMISSION,
    STORE_DELETE_PERMISSION,
];

export const READER_PERMISSIONS: string[] = [
    ORDER_READ_PERMISSION,

    BOOK_READ_PERMISSION,

    EVENT_READ_PERMISSION,

    LIBRARY_READ_PERMISSION,

    STORE_READ_PERMISSION,
];
